// 演示用知识图谱数据（中小学人工智能通识教育）
// 第一版内置 ~24 个知识点 + 关系边，覆盖设计方案第 22 节示例概念。
// 真实环境应来自「后端 / 知识卡片 / Agent 对话」的增量合并（见设计文档第 8 节）。

import type { KnowledgeEdge, KnowledgeNode } from './contracts';

const courseRef = (id: string, label: string) => ({ type: 'course' as const, id, label });
const convRef = (id: string, label: string, selectedText?: string) => ({
  type: 'conversation' as const,
  id,
  label,
  selectedText,
});
const cardRef = (id: string, label: string) => ({ type: 'knowledge-card' as const, id, label });

export const MOCK_NODES: KnowledgeNode[] = [
  {
    id: 'what-is-ai',
    title: '什么是 AI',
    summary: '人工智能是让机器模拟人类智能行为（感知、推理、学习、决策）的技术总称。',
    category: 'ai-basic',
    mastery: 'understood',
    importance: 3,
    confidence: 0.95,
    sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')],
  },
  {
    id: 'data',
    title: '数据',
    summary: '数据是 AI 学习规律的材料，包括文本、图像、声音等可被数字化的信息。',
    category: 'ai-basic',
    mastery: 'understood',
    importance: 3,
    confidence: 0.92,
    sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')],
  },
  {
    id: 'label',
    title: '标签',
    summary: '标签是人工标注的答案或类别，用于告诉模型「这张图是什么」。',
    category: 'ai-basic',
    mastery: 'learning',
    importance: 2,
    confidence: 0.9,
    sourceRefs: [convRef('m-12', 'AI 伴学对话 · 图像分类')],
  },
  {
    id: 'algorithm',
    title: '算法',
    summary: '算法是解决某类问题的明确步骤，机器学习算法从数据中自动总结规律。',
    category: 'ai-basic',
    mastery: 'learning',
    importance: 2,
    confidence: 0.88,
    sourceRefs: [courseRef('c2', 'AI 通识课 · 第 3 章')],
  },
  {
    id: 'ml',
    title: '机器学习',
    summary: '机器学习是 AI 的子领域，让计算机通过数据自动改进，而不依赖显式编程。',
    category: 'machine-learning',
    mastery: 'learning',
    importance: 3,
    confidence: 0.93,
    sourceRefs: [courseRef('c2', 'AI 通识课 · 第 3 章')],
  },
  {
    id: 'supervised',
    title: '监督学习',
    summary: '用「带标签的数据」训练模型，学习输入到输出的映射，如分类与回归。',
    category: 'machine-learning',
    mastery: 'learning',
    importance: 3,
    confidence: 0.9,
    sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')],
  },
  {
    id: 'unsupervised',
    title: '无监督学习',
    summary: '在无标签数据中发现隐藏结构或聚类，例如把相似图片自动分组。',
    category: 'machine-learning',
    mastery: 'unknown',
    importance: 2,
    confidence: 0.78,
    sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')],
  },
  {
    id: 'training-data',
    title: '训练数据',
    summary: '训练数据是模型用来学习规律的数据，其质量会直接影响模型表现。',
    category: 'machine-learning',
    mastery: 'learning',
    importance: 3,
    confidence: 0.94,
    sourceRefs: [
      convRef('m-12', 'AI 伴学对话 · 图像分类', '训练数据的质量会直接影响模型表现'),
      cardRef('k-03', '知识卡 · 训练数据'),
    ],
  },
  {
    id: 'test-data',
    title: '测试数据',
    summary: '测试数据是模型从未见过的数据，用于检验模型的真实泛化能力。',
    category: 'machine-learning',
    mastery: 'learning',
    importance: 2,
    confidence: 0.9,
    sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')],
  },
  {
    id: 'overfit',
    title: '过拟合',
    summary: '过拟合指模型死记硬背训练数据，导致在新的数据上表现变差。',
    category: 'machine-learning',
    mastery: 'review',
    importance: 3,
    confidence: 0.89,
    sourceRefs: [convRef('m-21', 'AI 伴学对话 · 过拟合'), cardRef('k-07', '知识卡 · 过拟合')],
    review: true,
  },
  {
    id: 'generalization',
    title: '泛化能力',
    summary: '泛化能力是模型处理未见过的新数据的能力，是评价模型好坏的核心指标。',
    category: 'machine-learning',
    mastery: 'review',
    importance: 3,
    confidence: 0.87,
    sourceRefs: [courseRef('c4', 'AI 通识课 · 第 5 章')],
    review: true,
  },
  {
    id: 'model',
    title: '模型',
    summary: '模型是机器学习从数据中总结出的「规律函数」，用来对新输入做预测。',
    category: 'machine-learning',
    mastery: 'understood',
    importance: 2,
    confidence: 0.91,
    sourceRefs: [courseRef('c2', 'AI 通识课 · 第 3 章')],
  },
  {
    id: 'features',
    title: '特征',
    summary: '特征是从原始数据中提取的、对任务有用的描述（如图片的边缘、颜色）。',
    category: 'machine-learning',
    mastery: 'learning',
    importance: 2,
    confidence: 0.85,
    sourceRefs: [courseRef('c4', 'AI 通识课 · 第 5 章')],
  },
  {
    id: 'cv',
    title: '计算机视觉',
    summary: '计算机视觉让机器「看懂」图像与视频，是 AI 的重要应用方向。',
    category: 'computer-vision',
    mastery: 'learning',
    importance: 3,
    confidence: 0.9,
    sourceRefs: [courseRef('c5', 'AI 通识课 · 第 6 章')],
  },
  {
    id: 'image-classification',
    title: '图像分类',
    summary: '图像分类是判断一张图片属于哪个类别的任务，是计算机视觉的基础问题。',
    category: 'computer-vision',
    mastery: 'learning',
    importance: 3,
    confidence: 0.92,
    sourceRefs: [
      convRef('m-12', 'AI 伴学对话 · 图像分类'),
      cardRef('k-03', '知识卡 · 训练数据'),
    ],
  },
  {
    id: 'cnn',
    title: '卷积神经网络',
    summary: '卷积神经网络（CNN）擅长从图像中提取局部特征，常用于图像分类。',
    category: 'computer-vision',
    mastery: 'unknown',
    importance: 2,
    confidence: 0.8,
    sourceRefs: [courseRef('c6', 'AI 通识课 · 第 7 章')],
  },
  {
    id: 'genai',
    title: '生成式 AI',
    summary: '生成式 AI 能创造新内容（文字、图像、音乐），而非仅仅做判断。',
    category: 'generative-ai',
    mastery: 'learning',
    importance: 3,
    confidence: 0.9,
    sourceRefs: [courseRef('c7', 'AI 通识课 · 第 8 章')],
  },
  {
    id: 'llm',
    title: '大语言模型',
    summary: '大语言模型（LLM）在海量文本上训练，能理解和生成自然语言。',
    category: 'generative-ai',
    mastery: 'learning',
    importance: 3,
    confidence: 0.88,
    sourceRefs: [convRef('m-30', 'AI 伴学对话 · 大模型')],
  },
  {
    id: 'diffusion',
    title: '扩散模型',
    summary: '扩散模型通过逐步去噪生成图像，是主流文生图技术的核心。',
    category: 'generative-ai',
    mastery: 'unknown',
    importance: 2,
    confidence: 0.76,
    sourceRefs: [courseRef('c8', 'AI 通识课 · 第 9 章')],
  },
  {
    id: 'bias',
    title: '数据偏差',
    summary: '数据偏差指训练数据不能代表真实世界，导致模型产生不公平或错误结论。',
    category: 'ai-ethics',
    mastery: 'review',
    importance: 3,
    confidence: 0.86,
    sourceRefs: [
      convRef('m-12', 'AI 伴学对话 · 图像分类', '训练集缺少某类人群会让模型带偏差'),
      cardRef('k-09', '知识卡 · 数据偏差'),
    ],
    review: true,
  },
  {
    id: 'ethic',
    title: 'AI 伦理',
    summary: 'AI 伦理关注人工智能带来的公平、安全、责任与对人类的影响。',
    category: 'ai-ethics',
    mastery: 'unknown',
    importance: 2,
    confidence: 0.82,
    sourceRefs: [courseRef('c9', 'AI 通识课 · 第 10 章')],
  },
  {
    id: 'privacy',
    title: '隐私保护',
    summary: '隐私保护要求在使用数据训练 AI 时，避免泄露个人敏感信息。',
    category: 'ai-ethics',
    mastery: 'unknown',
    importance: 2,
    confidence: 0.8,
    sourceRefs: [courseRef('c9', 'AI 通识课 · 第 10 章')],
  },
  {
    id: 'agent',
    title: 'AI Agent',
    summary: 'AI Agent 能自主规划、调用工具并完成多步骤任务，是当前 AI 应用热点。',
    category: 'other',
    mastery: 'learning',
    importance: 3,
    confidence: 0.85,
    sourceRefs: [convRef('m-40', 'AI 伴学对话 · Agent 工程')],
  },
  {
    id: 'prompt',
    title: '提示词',
    summary: '提示词是与大语言模型对话时给出的指令，写得好坏直接影响输出质量。',
    category: 'other',
    mastery: 'learning',
    importance: 2,
    confidence: 0.84,
    sourceRefs: [convRef('m-30', 'AI 伴学对话 · 大模型')],
  },
];

export const MOCK_EDGES: KnowledgeEdge[] = [
  { id: 'e1', source: 'what-is-ai', target: 'ml', relation: 'contains', directed: true, weight: 3, confidence: 0.95, sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')] },
  { id: 'e2', source: 'what-is-ai', target: 'cv', relation: 'contains', directed: true, weight: 3, confidence: 0.93, sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')] },
  { id: 'e3', source: 'what-is-ai', target: 'genai', relation: 'contains', directed: true, weight: 3, confidence: 0.92, sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')] },
  { id: 'e4', source: 'what-is-ai', target: 'agent', relation: 'contains', directed: true, weight: 2, confidence: 0.85, sourceRefs: [convRef('m-40', 'AI 伴学对话 · Agent 工程')] },
  { id: 'e5', source: 'ml', target: 'supervised', relation: 'contains', directed: true, weight: 3, confidence: 0.93, sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')] },
  { id: 'e6', source: 'ml', target: 'unsupervised', relation: 'contains', directed: true, weight: 2, confidence: 0.85, sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')] },
  { id: 'e7', source: 'ml', target: 'model', relation: 'related', directed: false, weight: 2, confidence: 0.88, sourceRefs: [courseRef('c2', 'AI 通识课 · 第 3 章')] },
  { id: 'e8', source: 'features', target: 'ml', relation: 'prerequisite', directed: true, weight: 2, confidence: 0.85, sourceRefs: [courseRef('c4', 'AI 通识课 · 第 5 章')] },
  { id: 'e9', source: 'training-data', target: 'supervised', relation: 'prerequisite', directed: true, weight: 3, confidence: 0.9, sourceRefs: [cardRef('k-03', '知识卡 · 训练数据')] },
  { id: 'e10', source: 'label', target: 'supervised', relation: 'prerequisite', directed: true, weight: 2, confidence: 0.88, sourceRefs: [convRef('m-12', 'AI 伴学对话 · 图像分类')] },
  { id: 'e11', source: 'training-data', target: 'image-classification', relation: 'prerequisite', directed: true, weight: 3, confidence: 0.91, sourceRefs: [convRef('m-12', 'AI 伴学对话 · 图像分类', '数据与标签是图像分类的前置知识')] },
  { id: 'e12', source: 'supervised', target: 'image-classification', relation: 'applies_to', directed: true, weight: 3, confidence: 0.9, sourceRefs: [courseRef('c5', 'AI 通识课 · 第 6 章')] },
  { id: 'e13', source: 'cv', target: 'image-classification', relation: 'contains', directed: true, weight: 3, confidence: 0.92, sourceRefs: [courseRef('c5', 'AI 通识课 · 第 6 章')] },
  { id: 'e14', source: 'cnn', target: 'image-classification', relation: 'applies_to', directed: true, weight: 2, confidence: 0.86, sourceRefs: [courseRef('c6', 'AI 通识课 · 第 7 章')] },
  { id: 'e15', source: 'overfit', target: 'generalization', relation: 'causes', directed: true, weight: 3, confidence: 0.89, sourceRefs: [convRef('m-21', 'AI 伴学对话 · 过拟合', '过拟合会导致泛化能力下降')] },
  { id: 'e16', source: 'training-data', target: 'model', relation: 'causes', directed: true, weight: 3, confidence: 0.9, sourceRefs: [convRef('m-12', 'AI 伴学对话 · 图像分类', '训练数据的质量会直接影响模型表现')] },
  { id: 'e17', source: 'model', target: 'generalization', relation: 'related', directed: false, weight: 2, confidence: 0.85, sourceRefs: [courseRef('c4', 'AI 通识课 · 第 5 章')] },
  { id: 'e18', source: 'overfit', target: 'training-data', relation: 'related', directed: false, weight: 2, confidence: 0.82, sourceRefs: [cardRef('k-07', '知识卡 · 过拟合')] },
  { id: 'e19', source: 'training-data', target: 'bias', relation: 'related', directed: false, weight: 3, confidence: 0.86, sourceRefs: [convRef('m-12', 'AI 伴学对话 · 图像分类', '训练集缺少某类人群会让模型带偏差')] },
  { id: 'e20', source: 'test-data', target: 'bias', relation: 'related', directed: false, weight: 2, confidence: 0.84, sourceRefs: [courseRef('c4', 'AI 通识课 · 第 5 章')] },
  { id: 'e21', source: 'training-data', target: 'test-data', relation: 'contrast', directed: false, weight: 2, confidence: 0.88, sourceRefs: [courseRef('c3', 'AI 通识课 · 第 4 章')] },
  { id: 'e22', source: 'bias', target: 'ethic', relation: 'related', directed: false, weight: 2, confidence: 0.83, sourceRefs: [courseRef('c9', 'AI 通识课 · 第 10 章')] },
  { id: 'e23', source: 'privacy', target: 'ethic', relation: 'related', directed: false, weight: 2, confidence: 0.82, sourceRefs: [courseRef('c9', 'AI 通识课 · 第 10 章')] },
  { id: 'e24', source: 'genai', target: 'llm', relation: 'contains', directed: true, weight: 3, confidence: 0.9, sourceRefs: [courseRef('c7', 'AI 通识课 · 第 8 章')] },
  { id: 'e25', source: 'genai', target: 'diffusion', relation: 'contains', directed: true, weight: 2, confidence: 0.82, sourceRefs: [courseRef('c8', 'AI 通识课 · 第 9 章')] },
  { id: 'e26', source: 'agent', target: 'llm', relation: 'applies_to', directed: true, weight: 2, confidence: 0.84, sourceRefs: [convRef('m-40', 'AI 伴学对话 · Agent 工程')] },
  { id: 'e27', source: 'prompt', target: 'llm', relation: 'prerequisite', directed: true, weight: 2, confidence: 0.83, sourceRefs: [convRef('m-30', 'AI 伴学对话 · 大模型')] },
  { id: 'e28', source: 'data', target: 'training-data', relation: 'related', directed: false, weight: 2, confidence: 0.85, sourceRefs: [courseRef('c1', 'AI 通识课 · 第 1 章')] },
  { id: 'e29', source: 'algorithm', target: 'ml', relation: 'related', directed: false, weight: 2, confidence: 0.84, sourceRefs: [courseRef('c2', 'AI 通识课 · 第 3 章')] },
  { id: 'e30', source: 'ethic', target: 'what-is-ai', relation: 'related', directed: false, weight: 1, confidence: 0.78, sourceRefs: [courseRef('c9', 'AI 通识课 · 第 10 章')] },
];
